<?php

/**
 * @file
 * Primary module hooks for Matterport Embed module.
 */

/**
 * Implements hook_theme().
 */
function matterport_embed_theme($existing, $type, $theme, $path)
{
  return [
    'matterport_embed' => [
      'variables' => [
        'height' => null,
        'width' => null,
        'url' => '',
        'classes' => [],
        'wrapper_classes' => [],
        'wrapper_inline_styles' => [],
        'iframe_allows' => '',
      ],
    ],
  ];
}
